input_data:
  application: "../data/raw/application_train.csv"
  bureau: "../data/raw/bureau.csv"
  previous_application: "../data/raw/previous_application.csv"

output_data:
  application: "../data/clean/application_clean.csv"
  bureau: "../data/clean/bureau_clean.csv"
  previous_application: "../data/clean/previous_application_clean.csv"

database:
  name: "home_credit"
  host: "localhost"
  user: "root"
